### PR TITLE
Homepage copy updates

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Updated the homepage with changes requested in the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- Fixed the copydoc metatag

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8039/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that the page matches the copy doc (note: the comments around images and quotes aren't addressed in this PR, I've asked Tytus if they're still valid and am waiting on a response)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4740

### CODE REVIEW

**Review by petesfrench — APPROVED** [review]
Looks good but I'm having an issue running microstack so I am unable to view it in browser. And there are some images in the doc, have they been changed already?

**Comment by sowasred2012** [comment]
@petesfrench do you mean the images mentioned in the comments?

**Comment by petesfrench** [comment]
@sowasred2012 yes

**Comment by petesfrench** [comment]
@sowasred2012 Just had a look in browser and it is good to go

**Pull request merged**
